### ISSUE TITLE
fatal error when compiling rules

### ISSUE THREAD

**Issue by nhnghia** [Montimage/5Greplay#14]
When compiling a rule using `compile` command, there is an error: 

```
 fatal error: plugin_header.h: No such file or directory
 #include "plugin_header.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by HK5G** [comment]
It is unclear to me when launching 5Greplay commands on command line which .xml (.so) file is called. For example, when typing: sudo ./5greplay replay -t 5g-sa.pcap -Xforward.nb-copies=2000 -Xforward.default=FORWARD, how can we know which Forward property is called ?

**Comment by nhnghia** [comment]
Normally, all properties will be verified. Thus all properties will be *called*. (Note that the `if_satisified` function of a property is called only when the boolean expressions of the property is satisfied).

To exclude a property from verification, you can put its id in `exclude-rules` of `engine` block in the config file.

**Comment by HK5G** [comment]
> Normally, all properties will be verified. Thus all properties will be _called_. (Note that the `if_satisified` function of a property is called only when the boolean expressions of the property is satisfied).
> 
> To exclude a property from verification, you can put its id in `exclude-rules` of `engine` block in the config file.

Actually, I am getting a configuration parameter overridden by another one. Unable to figure out where and how this is done:
mmt-5greplay: Overridden value of configuration parameter 'forward.nb-copies' by '2000'
mmt-5greplay: Overridden value of configuration parameter 'forward.default' by '0'

**Comment by nhnghia** [comment]
That has been done by `-X` parameters when you run 5Greplay, e.g., `-Xforward.nb-copies=2000 -Xforward.default=FORWARD`
