### ISSUE TITLE
Rule construction

### ISSUE THREAD

**Issue by AndreasSpateneder** [Montimage/5Greplay#17]
When reading the documentation on rule xml semantics it is not apparant how the property tree is constructed.
The documentation does not give examples of operator attributes and sample rules do not contain code examples,
making it hard to construct complex rules.

**Comment by nhnghia** [comment]
Thanks @AndreasSpateneder  for this report. Indeed the documentation is needed to improve a lot. We are trying to do it. A description of the rule's semantics and its example will be available soon.
