### ISSUE TITLE
info command shows type : Drop for forwarding rule

### ISSUE THREAD

**Issue by AndreasSpateneder** [Montimage/5Greplay#18]
Running the command ./5greplay info [path_to_rule] shows type as DROP when type_property is set to FORWARD.
Event_count shows 2 with one event in rule.

Rule:

```xml
<beginning>
    <embedded_functions><![CDATA[

]]></embedded_functions>

    <property property_id="1" delay_units="ms" delay_min="0" delay_max="0" 
        type_property="FORWARD" description="Packet sent by open5gs Access and Mobility Management Function (AMF).">

        <event event_id="1"  value="COMPUTE"
            description="Sent by AMF."
            boolean_expression="( ( sctp.src_port == 38412 ) &amp;&amp; ( #is_same_ipv4(ip.src, '127.0.0.5' ) ) )"/>

    </property>

</beginning>
```

Info Output:

> mmt-5greplay: 5Greplay v0.0.3-15ede75 using DPI v1.7.0.0 (a8ad3c2) is running on pid 4331
Found 1 rule.
1 - Rule id: 1
	- type            : DROP
	- events_count    : 2
	- variables_count : 2
	- variables       : ip.src (178.13), sctp.src_port (304.1)
	- description     : Packet sent by open5gs Access and Mobility Management Function (AMF).
	- if_satisfied    : 0x7f8916358ae0
	- version         : 0.0.3 (15ede75 - 2022-1-30 18:6:45), dpi version 1.7.0.0 (a8ad3c2)

**Comment by nhnghia** [comment]
Thanks @AndreasSpateneder  for this nice catch! Fixed!
