### ISSUE TITLE
Issue in compiling the ruels

### ISSUE THREAD

**Issue by Alicodee** [Montimage/5Greplay#37]
I am getting this error during compiling the rules.  would you please guide me to resolve this issue?

```bash
root@20b28097c6b7:/root/5greplay-0.0.6# ./5greplay compile rules/4.nas-smc-replay-attack.so rules/4.nas-smc-replay-attack.xml 
mmt-5greplay: 5Greplay v0.0.6-00c7cd6 using DPI v1.7.3 (86eba86) is running on pid 2881
rules/4.nas-smc-replay-attack.so.c:8:10: fatal error: plugin_header.h: No such file or directory
    8 | #include "plugin_header.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by warlock1302** [comment]
I am facing the same issue. Is there any fix for this?

**Comment by nhnghia** [comment]
The error occurs when compiling rules using the pre-compiled 5Greplay distribution. Consequently it does not include any header files together with the distribution. 

A work around for the moment is to get 5Greplay source code and compile it to get the executable file.
