### ISSUE TITLE
[amf] INFO: gNB-N2[127.0.0.1] connection refused!!!

### ISSUE THREAD

**Issue by ztms123** [Montimage/5Greplay#43]
### At first, it was this question（Failed to Decode ASN PDU）, but after reading the revised answers, it became like this
[https://github.com/Montimage/5Greplay/issues/38](https://github.com/Montimage/5Greplay/issues/38)

When I send a pcap file to AMF I am getting the below messages in amf.log
```
**yjq@ubuntu:/mnt/hgfs/job/5greplay-0.0.1$ sudo tail -f /var/log/open5gs/amf.log
12/13 06:27:02.912: [amf] INFO: [Added] Number of gNBs is now 1 (../src/amf/context.c:1232)
12/13 06:27:02.913: [amf] INFO: gNB-N2[127.0.0.1] max_num_of_ostreams : 30 (../src/amf/amf-sm.c:781)
12/13 06:27:03.001: [amf] INFO: gNB-N2[127.0.0.1] connection refused!!! (../src/amf/amf-sm.c:793)
12/13 06:27:03.001: [amf] INFO: [Removed] Number of gNBs is now 0 (../src/amf/context.c:1259)
12/13 06:27:04.937: [amf] INFO: gNB-N2 accepted[127.0.0.1]:57871 in ng-path module (../src/amf/ngap-sctp.c:114)
12/13 06:27:04.937: [amf] INFO: gNB-N2 accepted[127.0.0.1] in master_sm module (../src/amf/amf-sm.c:742)
12/13 06:27:04.978: [amf] INFO: [Added] Number of gNBs is now 1 (../src/amf/context.c:1232)
12/13 06:27:04.978: [amf] INFO: gNB-N2[127.0.0.1] max_num_of_ostreams : 30 (../src/amf/amf-sm.c:781)
12/13 06:27:05.041: [amf] INFO: gNB-N2[127.0.0.1] connection refused!!! (../src/amf/amf-sm.c:793)
12/13 06:27:05.041: [amf] INFO: [Removed] Number of gNBs is now 0 (../src/amf/context.c:1259)**
```

**Comment by ztms123** [comment]
> Can you please provide log of 5Greplay as well as the pcap file?

First of all, thanks for such a quick reply，
and analyse 5Greplay log  I know the pcap file is error

> mmt-5greplay: pcap_open failed for the following reason: unknown file format
pcap_open failed for the following reason: unknown file format

but how to get right pcap ?
I use   Quickstart  5greplay-0.0.1_Linux_x86_64.tar.gz version 
and then  this url is not exist
> wget https://github.com/Montimage/5GReplay/raw/main/docs/docs/tutorial/replay-open5gs/5g-sa.pcap

so  i git checkout v0.0.1 tag  use this path pcap  
eventually ，This error is generated

> 5Greplay-0.0.1\docs\docs\tutorial\replay-open5gs\5g-sa.pcap

**Comment by ztms123** [comment]
> Can you please provide log of 5Greplay as well as the pcap file?

I change another 5g-sa.pcap then the same error
5Greplay log as follow:

> mmt-5greplay: 5Greplay v0.0.1-d9f4cef using DPI v1.7.0.0 (a8ad3c2) is running on pid 97162
mmt-5greplay: Overridden value of configuration parameter 'forward.nb-copies' by '2000'
mmt-5greplay: Overridden value of configuration parameter 'forward.default' by '0'
mmt-5greplay: Ignore duplicated rule id 103 (Inject only packet from UE -> Core but not inversed direction)
mmt-5greplay: MMT-5Greplay 0.0.1 (d9f4cef - Sep  9 2021 10:20:49) is verifying 3 rules having 5 proto.atts using the main thread
mmt-5greplay: Analyzing pcap file 5g-sa.pcap
mmt-5greplay: Interrupted by signal 2
mmt-5greplay: Releasing resource ... (press Ctrl+c again to exit immediately)

and pcap is On branch main and path 
> 5Greplay\docs\docs\tutorial\replay-open5gs\5g-sa.pcap

![image](https://github.com/Montimage/5Greplay/assets/81799631/045d7d3c-f747-4dbf-87f3-d5f0397f628c)

**Comment by nhnghia** [comment]
Thank you for the details. Please check again the pcap file because the following url is existing (as I can download the `5g-sa.pcap` file). Maybe your download was interuptted so you got a malformed pcap file.

> and then this url is not exist
>> wget https://github.com/Montimage/5GReplay/raw/main/docs/docs/tutorial/replay-open5gs/5g-sa.pcap

**Comment by ztms123** [comment]
> https://github.com/Montimage/5GReplay/raw/main/docs/docs/tutorial/replay-open5gs/5g-sa.pcap

Thank you respond，but I use wget URL 
  **302 Found**

> yjq@ubuntu:/mnt/hgfs/job/5greplay-0.0.1$ wget https://github.com/Montimage/5GReplay/raw/main/docs/docs/tutorial/replay-open5gs/5g-sa.pcap
--2023-12-14 06:05:04--  https://github.com/Montimage/5GReplay/raw/main/docs/docs/tutorial/replay-open5gs/5g-sa.pcap
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Montimage/5GReplay/main/docs/docs/tutorial/replay-open5gs/5g-sa.pcap [following]
--2023-12-14 06:05:04--  https://raw.githubusercontent.com/Montimage/5GReplay/main/docs/docs/tutorial/replay-open5gs/5g-sa.pcap
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 0.0.0.0, ::
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... failed: Connection refused.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|::|:443... failed: Connection refused.

Then  I use Browser access
![image](https://github.com/Montimage/5Greplay/assets/81799631/2ca46a59-b98e-45a3-8da2-f4501a0f0da0)

**Comment by nhnghia** [comment]
I'm not sure for which reason you cannot download the pcap file. If you can clone the 5Greplay repository from GitHub, then you can see the pcap file at  [`docs/docs/tutorial/replay-open5gs`](https://github.com/Montimage/5Greplay/tree/main/docs/docs/tutorial/replay-open5gs)

**Comment by warlock1302** [comment]
hi @nhnghia. i am facing same issue with UERANSIM and Open5gs. i have attached logs and pcap for your reference. I am facing this issue in linux machine. i have
[Archive.zip](https://github.com/Montimage/5Greplay/files/13757036/Archive.zip)
 another machine running on Fedora where there is no issue.

**Comment by nhnghia** [comment]
Hi @warlock1302. Thank you for the information. Unfortunately I'm not able to reproduce the issue thus have no idea what would be.

Are there any different configuration of Open5Gs between these 2 machines?
Are you able to connect UERASIM to Open5Gs? If yes, try to capture its packets to a pcap file, then use the latter to replay

**Comment by nhnghia** [comment]
Hi @ztms123 , @warlock1302  ,

Please give a test with the latest version https://github.com/Montimage/5Greplay/commit/bb5d7f8797c3f7bf84c8ef92ed2e4926bf41b99e

Feel free to reopen this issue if it still exists in your tests!
