### ISSUE TITLE
5greplay Replays Entire pcap Instead of Single Intended Packet in Offline

### ISSUE THREAD

**Issue by HansJack1999** [Montimage/5Greplay#44]
I was writing an XML file to specifically replay an Authentication request in offline mode, using 'test2.pcap' as the input. However, upon inspecting the logs and using Wireshark, I noticed that 5greplay had replayed all the packets from the pcap file I provided(There are 1,942 messages in tset2.pcap, and log shows that it replays all 1,942 messages), instead of just the single packet I intended.
I don't know what went wrong. Because neither open5gs nor 5greplay has reported any errors. I have no way to start.I would be deeply grateful to anyone who can provide insights or answers to my questions.
I used the following command：
`sudo ./5greplay replay -t test2.pcap -Xforward.nb-copies=1 -Xforward.default=FORWARD > log.txt 2>&1`

Here are the rules I used, the log output from 5grepaly, and the input pcap files I used and the pcap files I captured on replay
The xml file is as follows：
```jsx
<beginning>
<embedded_functions><![CDATA[

static void em_forward(
      const rule_info_t *rule, int verdict, uint64_t timestamp,
      uint64_t counter, const mmt_array_t * const trace ){
   const char* trace_str = mmt_convert_execution_trace_to_json_string( trace, rule );
   //forward the original packet (without any modification)
   forward_packet();
}
]]></embedded_functions>
<property property_id="99" type_property="FORWARD"  description="Replay the Authentication request"
    if_satisfied="em_forward"> 
    <event value="COMPUTE" event_id="1" 
        description="Downlink NAS Transport, Authentication request"
           boolean_expression="((ngap.procedure_code == 4) &amp;&amp; (nas_5g.message_type == 86))"/>
</property>

</beginning>
```
My 5greplay log is as follows:
```jsx
mmt-5greplay: 5Greplay v0.0.7-eaef12c using DPI v1.7.10 (6dc79073) is running on pid 9174
mmt-5greplay: Overridden value of configuration parameter 'forward.nb-copies' by '1'
mmt-5greplay: Overridden value of configuration parameter 'forward.default' by '0'
mmt-5greplay: MMT-5Greplay 0.0.7 (eaef12c - Dec 13 2023 20:57:47) is verifying 1 rules having 2 proto.atts using the main thread
mmt-5greplay: Registered attribute to extract: 903.1
mmt-5greplay: Registered attribute to extract: 904.2
mmt-5greplay: Analyzing pcap file test2.pcap
        1942 packets received
        1942 messages received
           1 alerts generated
mmt-5greplay: Number of packets being successfully forwarded: 1942, dropped: 0
Number of packets being successfully forwarded: 1942, dropped: 0
 - rule 99 generated 1 verdicts
```
The following is the pcap file：
[pcapfile.zip](https://github.com/Montimage/5Greplay/files/13667874/pcapfile.zip)

**Comment by HansJack1999** [comment]
I also tested the official rules and found that the modification function did not work at all. For example, I used rule 10, but none of the values were changed. 5greplay forwards the entire test2.pcap directly. No new logs appear in the amf log

**Comment by nhnghia** [comment]
Hi @HansJack1999 ,

If you want to inject only the packets which are satisfait the `FORWARD` rules, then you should use `-Xforward.default=DROP` parameter.

**Comment by HansJack1999** [comment]
@nhnghia  Thank you so much for your assistance!

**Comment by HansJack1999** [comment]
I used the tool to replay messages from the initial registration to learn about 5G.  When I replayed the `InitialUEMessage Registration request`, 5GReplay indicated that the messages were successfully replayed, and I was able to capture them in wireshark loopback. However, I couldn't find any corresponding entries in the open5gs AMF log. I'm puzzled about this issue and would greatly appreciate any guidance you could offer.
![2023-12-18 10-09-43 的屏幕截图](https://github.com/Montimage/5Greplay/assets/57088895/17def0e0-6dc3-4b86-9b63-cad275800b0c)

![2023-12-18 10-10-26 的屏幕截图](https://github.com/Montimage/5Greplay/assets/57088895/9baeb79e-b64d-4d83-a925-f0ade8647b26)

**Comment by HansJack1999** [comment]
Thank you very much for your response. I am currently using open5gs version v2.6.6. Based on the version you mentioned, I will conduct some additional tests.
