### ISSUE TITLE
 gNB connection refused with srsRAN and Open5gs

### ISSUE THREAD

**Issue by ayamoheddine** [Montimage/5Greplay#45]
Hello, 
I want to study the behavior of the 5g network when some messages are replayed and re-injected in the network. The network is based on srsRAN for enb and open5gs for the core network. I tested my configurations on a real UE and a simulated one, however with the same issue. 
Please find attached the conf files and log from 5greplay and the pcap file I want to re-inject. 

Your help is highly appreciated. 

![amf_log](https://github.com/Montimage/5Greplay/assets/70331394/23449685-21d4-41a5-963b-d8eb5ca13cac)

[conf_files.zip](https://github.com/Montimage/5Greplay/files/14221259/conf_files.zip)

**Comment by nhnghia** [comment]
Hi @ayamoheddine ,

Please give a test with the latest version https://github.com/Montimage/5Greplay/commit/bb5d7f8797c3f7bf84c8ef92ed2e4926bf41b99e

Feel free to reopen this issue if it still exists in your test
